name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: 'npm'
    - run: npm ci
    - run: npm run build
